### ISSUE TITLE
WebEdit: Extension Mechanism

### ISSUE THREAD

**Issue by lippisch** [xwic/appkit#21]
The GenericEditor should allow further customization by developing Extensions for it, using the Appkit-Extension mechanism. To simplify it, we may offer multiple extension points for different purposes:
1. to add an action to the toolbar
2. to add a general editor listener - which listens to all the events and can react, i.e. add extra validation before saving etc.
3. Something to place content on the editor panels, i.e. add another tab with some special content that is managed by the extension
4. An extension point to add a TableViewer below that is related to the entity above

**Comment by vzhovtyuk** [comment]
Under all editor events i think make sense to have extensions for the following listeners:
de.xwic.appkit.webbase.editors.events.EditorListener
de.xwic.appkit.webbase.toolkit.editor.IEditorModelListener
de.jwic.events.ValueChangedListener

**Comment by lippisch** [comment]
For the TableViewer below the editor, we decided to add additional configuration options into the editor configuration XML that allows  to add lists or other custom content below. Here is a sample:

```xml
	<subTabs>
		<subtab title="Contacts">
			<listView type="IContact" filterOn="customer" listProfile="blabla"/>
		</subtab>
		<subtab title="Calculator">
			<custom class="de.bla.bla.CustomContentCreator"/>
		<sub/tab>
	</subTabs>
```
