### ISSUE TITLE
Boolean custom column filter layout askew

### ISSUE THREAD

**Issue by adrianionescu** [xwic/appkit#9]
The radio buttons for a boolean custom column filter have jumped to the next row.

See the attached screenshot - the radio buttons should be right under Sort True to False.

![screenshot_14](https://cloud.githubusercontent.com/assets/4354613/13114395/93a0bc14-d593-11e5-8290-6716f75f649c.png)

**Comment by vzhovtyuk** [comment]
After patch:
![boolean_column_filter](https://cloud.githubusercontent.com/assets/8643495/13179971/e3548864-d726-11e5-8af5-400c4f669996.png)

**Comment by vzhovtyuk** [comment]
Fixed in  vitaliy_boolean_custom_column_filter
